# Notification Options
notifications:
  email: false

# Regent supports Node.js v8
language: node_js
node_js:
  - '8' # LTS as of 2017-12-31

# Operating Systems
os:
  - linux
  - osx

# Branches that can trigger Travis-CI
branches:
  only:
    - master        # Master

# declare your environment variables
env:
  # matrix variables will create a new build for each specified variable
  matrix:
    - NODE_ENV=development

install:
  - npm install
  - npm install mocha

script:
  - npm test