environment:
  nodejs_version: "8"
  matrix:
    - NODE_ENV: development
build: off
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - node --version
  - npm --version
  - npm run test
